# Generated by Django 5.1 on 2024-09-24 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_alter_loginuser_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginuser',
            name='token',
        ),
    ]
