# Generated by Django 5.1 on 2024-09-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_remove_loginuser_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginuser',
            name='token',
            field=models.TextField(null=True),
        ),
    ]
