# Generated by Django 5.1 on 2024-09-24 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_recipe', '0001_initial'),
        ('user_auth', '0006_loginuser_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_auth.loginuser'),
        ),
    ]
