# Generated by Django 5.1 on 2024-09-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('VEG', 'VEG'), ('NON-VEG', 'NON-VEG')], max_length=10)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('ingredients', models.TextField()),
                ('method', models.TextField()),
            ],
        ),
    ]
